config/routes.rb
Rails.application.routes.draw do

  root "accueil#index"
  resources :accueil, only: [:index]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]

  resources :gossip do
    resources :comment
  end
  resources :user, only: [:show, :new, :create]
  resources :city, only: [:show]
  resources :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags
  has_many :comments
  has_many :likes

  validates :title,
    presence: true,
    length: { maximum: 30 }

  validates :content,
    presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  validates :last_name,
    presence: true

  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    presence: true

  has_secure_password
  validates :password,
    presence: true

  validates :password_confirmation,
    presence: true

class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
    @city = City.find(params[:id])
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour afficher la ville que vous cherchez"
        redirect_to new_session_path
      end
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

before_action :authenticate_user, only: [:new, :create, :edit, :destroy]

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all.where(gossip_id: params[:id])
    @tags = Tag.all
  end

  def new
    p '*' * 60
    p params
    p '*' * 60
    @gossip = Gossip.new()
    @tags = Tag.all
  end

  def create
    p '*' * 60
    p params
    p '*' * 60
    @tags = Tag.all
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

      if @gossip.save
        flash[:success] = "Votre potin a été créé!"
        redirect_to :root
      else
        flash[:danger] = "Une erreur est survenue, veuillez réessayer"
        render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)

    if @gossip.update(post_params)
      flash[:success] = "Votre potin a été modifié!"
      redirect_to gossip_path(@gossip.id)
    else
      flash[:danger] = "Une erreur est survenue, veuillez réessayer"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])

    if @gossip.destroy
      flash[:success] = "Votre potin a été supprimé avec succès!"
      redirect_to :root
    else
      flash[:danger] = "Une erreur est survenue, veuillez réessayer"
      render gossip_path
    end
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour accéder à la page des potins"
        redirect_to new_session_path
      end
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour accéder à la page de la team"
        redirect_to new_session_path
      end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
    @user = User.find(params[:id])
  end

  def new
    p params
    @user = User.new()
    @cities = City.all
  end

  def create
    p '*' * 20
    p params
    p '*' * 20
    @cities = City.all


    @user = User.new( first_name: params[:first_name],
                      last_name: params[:last_name],
                      email: params[:email],
                      description: params[:description],
                      age: params[:age],
                      city_id: params[:city],
                      password: params[:password],
                      password_confirmation: params[:password_confirmation]
                    )

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Votre compte a été créé avec succès!"
      redirect_to :root
    else
      flash[:danger] = "Une erreur est survenue, veuillez réessayer"
      render :new
    end
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour accéder à la page de l'utilisateur"
        redirect_to new_session_path
      end
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
 end

 def logged_in?
   !current_user.nil?

 end

 def forget(user)
     user.forget
     cookies.delete(:user_id)
     cookies.delete(:remember_token)
   end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def is_current_author(userid)
    if current_user.nil? || current_user.id != userid
      false
    else
      true
    end
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<br>
<h2 class="display-4 text-center">Ville n°<%= @city.id%></h2>
<p class="lead text-center">
  ici tu pourras retrouver les informations de la ville que tu recherche.
</p>

<hr width="75%" color=white>
<br>

  <div class="card bg-light mx-auto shadow rounded" style="max-width: 40rem;">
    <div class="card-body">
      <h5 class="card-text"><span class="font-weight-bold">Nom: </span> <br> <span class="text-dark small"><%= @city.name %> </span></h5>
      <hr width="75%" color=white>
      <h6 class="card-text"><span class="font-weight-bold">Code postal: </span> <br> <span class="text-dark small"><%= @city.zip_code %></span></h6>
    </div>
  </div>
<br>

<hr width="75%" color=white>
<br>

<div class="container">
  <div class="row">
    <% @city.users.each do |user| %>
	    <% user.gossips.each do |gossip| %>
        <div class="card bg-light mx-auto text-center shadow bg-light rounded" style="width: 20rem;">
          <div class="card-header"><%= link_to "Potin N°#{gossip.id}", gossip_path(gossip.id), :class => "link text-dark"%></div>
        <div class="card-body">
          <h5 class="card-title">Titre: <%= gossip.title %></h5>
          <hr width="30%" color=white>
          <h5 class="card-title">Contenu: <%= gossip.content %></h5>
          <hr width="30%" color=white>
          <p class="card-text text-muted">Auteur: <%= link_to gossip.user.first_name + ' ' + gossip.user.last_name, user_path(gossip.user.id), :class => "link text-dark"%></p>
        </div>
        </div>
      <% end %>
    <% end %>
 </div>
</div>

<br>
<div class="text-center"><%= link_to "Retour à la page principal", root_path, :class => "btn btn-secondary btn-sm link"%></div>

app/views/gossip/edit.html.erb
<br>
<h2 class="display-4 text-center">Potin n°<%= @gossip.id%></h2>
<p class="lead text-center">
  ici tu pourras éditer facilement le potin que tu cherchais.
</p>

<hr width="75%" color=white>
<br><br>

<%= form_for @gossip do |gossip| %>
  <div class="card bg-light mx-auto text-center shadow bg-light rounded" style="max-width: 40rem;">
    <div class="card-header">Titre: <%= gossip.text_field :title %></div>
    <div class="card-body">
      <h5 class="card-title">Contenu:</h5>
      <%= gossip.text_field :content %>
      <hr width="30%" color=white>
      <p class="card-text text-muted">Auteur: <%= @gossip.user.first_name + ' ' + @gossip.user.last_name%></p>
      <hr width="30%" color=white>
      <p class="card-text text-muted">Ville: <%= @gossip.user.city.name%></p>
      <hr width="30%" color=white>
      <%= submit_tag "Mettre à jour", :class => "btn btn-info"%>
    </div>
  </div>
<% end %>

<br>
<div class="text-center"><%= link_to "Retour à la page principal", root_path, :class => "btn btn-secondary btn-sm link"%></div>

app/views/gossip/new.html.erb
<br>

<h2 class="display-4 text-center">Créez votre potin</h2>
<p class="lead text-center">
  ici vous pouvez facilement créer votre propre potin.
</p>

<hr width="75%" color=white>

<br>

<div class="container">
    <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Titre' %>
        <%= text_field_tag 'title', @gossip.title, :class => "form-control"%>
<br>
        <%= label_tag 'Contenu' %>
        <%= text_area_tag 'content', @gossip.content, :class => "form-control"%>
<br>
<br>

      <%= submit_tag "Envoyer", :class => "btn btn-info"%>
    <% end %>
</div>

<br>
<div class="text-center"><%= link_to "Retour à la page principal", root_path, :class => "btn btn-secondary btn-sm link"%></div>

app/views/gossip/show.html.erb
<br>
<h2 class="display-4 text-center">Potin n°<%= @gossip.id%></h2>
<p class="lead text-center">
ici tu pourras retrouver le potin que tu recherche.
</p>

<hr width="75%" color=white>
<br>

<div class="card bg-light mx-auto text-center shadow bg-light rounded" style="max-width: 40rem;">
  <div class="card-header">Titre: <%= @gossip.title %></div>
  <div class="card-body">
    <h5 class="card-title">Contenu: <%= @gossip.content %></h5>
      <hr width="30%" color=white>
    <p class="card-text text-muted">Auteur: <%= link_to @gossip.user.first_name + ' ' + @gossip.user.last_name, user_path(@gossip.user.id), :class => "link text-dark"%></p>
      <hr width="30%" color=white>

    <p class="card-text small text-muted"><%= @gossip.created_at.strftime("Crée le %-d-%m-%Y à %Hh%M") %></p>

      <% if is_current_author(@gossip.user[:id]) %>
        <hr width="30%" color=white>
        <p class="card-link d-inline"><%= link_to "Editer", edit_gossip_path(@gossip.id), :class => "text-info"%></p>
        <p class="card-link inline d-inline"><%= link_to "Supprimer", gossip_path(@gossip.id), :class => "text-danger", data: { confirm: "Etes-vous sur de vouloir supprimer le potin ?", method: 'DELETE' }%></p>
      <% end %>
  </div>
</div>

<br>
<hr width="75%" color=white>
<br>

<h3 class="text-center">Commentaire du potins</h3>
<div class="lead text-center">
  ici tu pourras retrouver tous les commentaires du potin.
</div>

<br>

<% if current_user %>
  <div class="text-center"><%= link_to "Ecrire un commentaire", new_gossip_comment_path(@gossip.id), :class => "btn btn-info link"%></div>
<% else %>
  <div class="text-center">
    <button class="btn btn-info disabled">Ecrire un commentaire</button>
  </div>
<% end %>

<br>
<hr width="75%" color=white>
<br>

<div class="container">
  <div class="row">
    <% @comments.each do |c| %>
  <div class="card w-75 mx-auto shadow bg-light" style="max-width: 100rem;">
    <h5 class="card-header"><%= User.find(c.user_id).first_name %> <%= User.find(c.user_id).last_name %></h5>
    <div class="card-body">
      <p class="card-text"><%= c.content %></p>
      <p class="card-text small text-muted"><%= c.created_at.strftime("Crée le %-d-%m-%Y à %Hh%M") %></p>

    <% if is_current_author(c.user[:id]) %>
      <hr width="90%" color=white>
      <p class="card-link d-inline text-"><%= link_to "Editer", edit_gossip_comment_path(@gossip.id, c.id), :class => "text-info"%></p>
      <p class="card-link d-inline"><%= link_to "Supprimer", gossip_comment_path(@gossip.id, c.id), :class => "text-danger", data: { confirm: "Etes-vous sur de vouloir supprimer le commentaire ?", method: 'DELETE' }%></p>
    <% end %>

    </div>
  </div>
  <% end %>
</div>
</div>

<br>
<div class="text-center"><%= link_to "Retour à la page principal", root_path, :class => "btn btn-secondary btn-sm link"%></div>

app/views/user/new.html.erb
<br>

<h2 class="display-4 text-center">Créez votre compte</h2>
<p class="lead text-center">
  ici vous pouvez facilement créer votre propre compte.
</p>

<hr width="75%" color=white>

<br>

<div class="container">
    <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Prénom' %>
        <%= text_field_tag 'first_name', nil, type: "first_name", class: "form-control mb-4", placeholder: "Votre prénom" %>

        <%= label_tag 'Nom' %>
        <%= text_field_tag 'last_name', nil, type: "last_name", class: "form-control mb-4", placeholder: "Votre nom" %>

        <%= label_tag 'E-mail' %>
        <%= text_field_tag 'email', nil, type: "email", class: "form-control mb-4", placeholder: "Votre E-mail" %>

        <%= label_tag 'Description (optionel)' %>
        <%= text_field_tag 'description', nil, type: "description", class: "form-control mb-4", placeholder: "Décrivez-vous" %>

        <%= label_tag 'Age (optionel)' %>
        <%= text_field_tag 'age', nil, type: "age", class: "form-control mb-4", placeholder: "Votre Age" %>

        <%= label_tag 'Ville' %>
        <%= select_tag 'city', options_for_select(@cities.collect{ |c| [c.name, c.id] }), class: "form-control mb-4"%>

        <%= label_tag 'Mot de passe' %>
        <%= text_field_tag 'password', nil, type: "password", class: "form-control mb-4", placeholder: "Mot de passe" %>

        <%= label_tag 'Confirmer votre mot de passe'%>
        <%= text_field_tag 'password_confirmation', nil, type: "password", class: "form-control mb-4", placeholder: "Confirmation" %>


      <%= submit_tag "Créer mon compte!", :class => "btn btn-info btn-block my-4"%>
    <% end %>

    <p>Déjà un compte ?
        <%= link_to 'Connectez-vous!', new_session_path %>
    </p>

</div>


<% if @user.errors.any? %>
  <p>Nous n'avons pas réussi à créer le profile pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/user/show.html.erb
<br>
<h2 class="display-4 text-center">Utilisateur n°<%= @user.id%></h2>
<p class="lead text-center">
  ici tu pourras retrouver les informations de l'utilisateur que tu recherche.
</p>

<hr width="75%" color=white>
<br><br>

  <div class="card bg-light mx-auto shadow bg-light rounded" style="max-width: 40rem;">
    <div class="card-header"><span class="font-weight-bold">Nom: </span><%= @user.first_name + ' ' + @user.last_name %></div>
    <div class="card-body">
      <h5 class="card-text"><span class="font-weight-bold">Description: </span> <br> <span class="text-dark small"> <%= @user.description %> </span></h5>
      <hr width="30%" color=white>
      <h5 class="card-text"><span class="font-weight-bold">Age: </span> <span class="text-dark small"> <%= @user.age %> </span></h5>
      <hr width="30%" color=white>
      <h5 class="card-text"><span class="font-weight-bold">Email: </span> <span class="text-dark small"> <%= @user.email %> </span></h5>
      <hr width="30%" color=white>
      <h5 class="card-text"><span class="font-weight-bold">Ville: </span> <span> <%= link_to @user.city.name, city_path(@user.city.id), :class => "text-dark small link" %> </span></h5>
    </div>
  </div>

  <br>
  <div class="text-center"><%= link_to "Retour à la page principal", root_path, :class => "btn btn-secondary btn-sm link"%></div>