config/routes.rb
Rails.application.routes.draw do

  root "accueil#index"
  resources :accueil, only: [:index]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]

  resources :gossip do
    resources :comment
  end
  resources :user, only: [:show, :new, :create]
  resources :city, only: [:show]
  resources :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags
  has_many :comments
  has_many :likes

  validates :title,
    presence: true,
    length: { maximum: 30 }

  validates :content,
    presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  validates :last_name,
    presence: true

  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    presence: true

  has_secure_password
  validates :password,
    presence: true

  validates :password_confirmation,
    presence: true

class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  before_action :authenticate_user, only: [:index]
  def index
    @gossips = Gossip.all
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour accéder à la page d'accueil"
        redirect_to new_session_path
      end
    end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
    @city = City.find(params[:id])
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour afficher la ville que vous cherchez"
        redirect_to new_session_path
      end
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour accéder à la page de la team"
        redirect_to new_session_path
      end
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
 end

 def logged_in?
   !current_user.nil?

 end

 def forget(user)
     user.forget
     cookies.delete(:user_id)
     cookies.delete(:remember_token)
   end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def is_current_author(userid)
    if current_user.nil? || current_user.id != userid
      false
    else
      true
    end
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accueil/index.html.erb
<br>
<% if current_user %>
<h2 class="display-4 text-center">Bienvenue <%= current_user.first_name %></h2>
<% else %>
<h2 class="display-4 text-center">Bienvenue sur la page des potins</h2>
<% end %>
<p class="lead text-center">
  ici tu pourras retrouver tous les potins du site internet.
</p>

<hr width="75%" color=white>
  <% if current_user %>
    <div class="text-center"><%= link_to "Créez votre potin", new_gossip_path, :class => "btn btn-info link"%></div>
  <% else %>
    <div class="text-center">
      <button class="btn btn-info disabled">Créez votre potin</button>
    </div>
  <% end %>
<hr width="75%" color=white>
<br>
<div class="container">
     <div class="row">
       <% @gossips.order(:id).reverse.each do |gossip| %>
         <div class="col-md-4">
           <div class="card text-center shadow bg-light rounded" style="width: 20rem;">
             <div class="bg-light">
               <div class="card-header"><%= link_to gossip.title, gossip_path(gossip.id), :class => "link text-dark"%></div>
               <div class="card-body">
                 <h5 class="card-title"><%= gossip.content %></h5>
                 <footer class="blockquote-footer"><%= link_to gossip.user.first_name + ' ' + gossip.user.last_name, user_path(gossip.user.id), :class => "link text-dark"%></footer>
               </div>
             </div>
           </div> <br>
         </div>
       <% end %>
     </div>
</div>