config/routes.rb
Rails.application.routes.draw do

  root "accueil#index"
  resources :accueil, only: [:index]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]

  resources :gossip do
    resources :comment
  end
  resources :user, only: [:show, :new, :create]
  resources :city, only: [:show]
  resources :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags
  has_many :comments
  has_many :likes

  validates :title,
    presence: true,
    length: { maximum: 30 }

  validates :content,
    presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  validates :last_name,
    presence: true

  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    presence: true

  has_secure_password
  validates :password,
    presence: true

  validates :password_confirmation,
    presence: true

class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
    @city = City.find(params[:id])
  end

  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Connectez-vous pour afficher la ville que vous cherchez"
        redirect_to new_session_path
      end
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
 end

 def logged_in?
   !current_user.nil?

 end

 def forget(user)
     user.forget
     cookies.delete(:user_id)
     cookies.delete(:remember_token)
   end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def is_current_author(userid)
    if current_user.nil? || current_user.id != userid
      false
    else
      true
    end
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
      <%= link_to root_path do %>
         <%= image_tag "https://image.noelshack.com/fichiers/2019/07/5/1550243990-brand-logo.png", :class => "navbar-brand",:width => "100", :height => "60", :alt => "LogoGossip" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Team", team_index_path, class: "nav-item nav-link text-light" %>
          <%= link_to "Contact", contact_index_path, class: "nav-item nav-link text-light" %>
        </div>
        <% if current_user %>
        <i class="fas fa-sign-out-alt ml-auto"></i><%= link_to "Se déconnecter", session_path(session[:user_id]), method: :delete, :class => 'nav-item nav-link text-light' %>
        <% else %>
        <div class="dropdown ml-auto">
          <button class="btn btn-light btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            S'inscrire / Se connecter
          </button>
          <div class="dropdown-menu text-center" aria-labelledby="dropdownMenuButton">
            <%= link_to 'INSCRIPTION', new_user_path, class: "dropdown-item ml-auto"%>
            <hr width="50%" color=white>
            <%= link_to 'SE CONNECTER', new_session_path, class: "dropdown-item ml-auto"%>
          </div>
        </div>
        <% end %>
      </div>
    </nav>

    <% flash.each do |key, val| %>
      <div class="text-center alert alert-<%= key %>"><%= val %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>



    <%= yield %>
    <div class="container">
      <hr width="75%" color=white>
      <footer class="footer text-center">
        <div class="container">
          <p class="text-muted small">© T.W | 2019</p>
        </div>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-confirmation2/dist/bootstrap-confirmation.min.js"></script>
  </body>
</html>